[package]
name = "rustydomo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="broker"
path = "src/broker/bin/main.rs"


[dependencies]
env_logger = "0.9.0"
log = "0.4.17"
zmq = "0.9.2"
